config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "foods#index"

  resources :foods, only: [:index, :new, :create, :destroy]
  resources :public_recipes, only: [:index]

  resources :recipes, only: [:index, :new, :create, :destroy, :show, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
    resources :general_shopping_lists, only: [:index]
  end
  resources :inventories, only: [:index, :new, :create, :destroy, :show] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end
  
  devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Recipe, user_id: user.id
      can :manage, Food, user_id: user.id
      can :manage, Recipe do |recipe|
        recipe.user == user || recipe.public == true || !recipe.user_id?
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 50 }
  validates :measurementUnit, presence: true
  validates :price, presence: true

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy
  has_many :inventory, through: :inventory_foods, dependent: :destroy
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
  has_many :foods, through: :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food
  belongs_to :inventory
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  # validates :quantity, presence: true
  # validates :food_id, presence: true
  # validates :recipe_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  validates :name, presence: true
  has_many :inventories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_up_path_for(_resource)
    root_path
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def new
    @user = current_user
    @food = Food.new
  end

  def create
    @food = current_user.foods.create(food_params)
    if @food.save
      flash[:success] = 'Food created succesfully'
      redirect_to foods_url
    else
      render 'new'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:success] = 'Food deleted successfully'
    redirect_to root_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurementUnit, :price)
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @inventories = Inventory.all
    @inventory = Inventory.find_by(id: params[:id])
  end

  def new
    @user = current_user
    @inventory = Inventory.new
  end

  def show
    @inventory = Inventory.find(params[:id])
    @foods = InventoryFood.all
  end

  def create
    @inventory = current_user.inventories.new(inventory_params)
    if @inventory.save
      flash[:success] = 'Inventory created succesfully'
      redirect_to inventories_url
    else
      render 'new'
    end
  end

  def destroy
    @inventory = Inventory.find_by(id: params[:id])
    @inventory.destroy
    flash[:success] = 'Inventory deleted successfully'
    redirect_to inventories_url
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :quantity)
  end
end

app/controllers/inventory_foods_controller.rb
class InventoryFoodsController < ApplicationController
  def new
    @inventory = Inventory.find_by(params[:inventories_id])
    @inventory_food = @inventory.inventory_foods.new
  end

  def create
    @inventory = Inventory.find(params[:inventory_id])
    @inventory_food = @inventory.inventory_foods.create(inventory_food_params)
    if @inventory_food.save
      flash[:success] = 'Food created succesfully'
      redirect_to inventories_url
    else
      render 'new'
    end
  end

  def destroy
    @inventory_food = InventoryFood.find(params[:id])
    @inventory_food.destroy
    flash[:success] = 'Food deleted successfully'
    redirect_to inventories_path
  end

  private

  def inventory_food_params
    params.require(:inventory_food).permit(:quantity, :food_id)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @user = current_user
    @total_item = Recipe.all.count
    @prices = Food.all.sum(:price)
    @all_recipe = Recipe.all
    @public_recipes = @all_recipe.where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.create(recipe_food_params)
    if @recipe_food.save
      flash[:success] = 'Food created succesfully'
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    flash[:success] = 'Food deleted successfully'
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
    @recipe = Recipe.find_by(id: params[:id])
  end

  def new
    @user = current_user
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @foods = RecipeFood.all
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      flash[:success] = 'Recipe created succesfully'
      redirect_to recipes_url
    else
      render 'new'
    end
  end

  def destroy
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.destroy
    flash[:success] = 'Recipe deleted successfully'
    redirect_to recipes_url
  end

  def update
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.update_attribute(:public, true)
    redirect_to recipes_url
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparationTime, :cookingTime, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inventories/index.html.erb
<div>
<h1>Inventory List</h1>

<div > <%= link_to 'New Inventory', new_inventory_path %></div>

  <% current_user.inventories.each do |inv| %>
    <div>
    <%= link_to 'See inventory', inventory_path(inv.id) %>
    <h2><%= inv.name %></h2>
    <%= button_to "Delete Inventory", inventory_path(inv.id), method: :delete, 
      data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim .</p>

    <% end %>
</div>

app/views/inventories/new.html.erb
<h1 class='text-center mb-3'>New Inventory</h1>

<div class='mb-5'>
  <%= form_with(model: @inventory, url: inventories_path) do |f| %>

      <div class="row form ml-4">
    <div class= "form-group d-flex mb-4" >
      <%= f.label "Name:", class: "col-sm-2 col-form-label text-end mx-4" %> 
      <div class = "col-sm-7" >
      <%= f.text_field :name,   class:"form-control", placeholder: "Enter food name", autofocus: true %>
      </div>
    </div>
    
    <div class= "form-group d-flex" >
      <div class= "col-sm-2  mx-4"></div>
      <%= f.submit class: "btn btn-lg btn-warning submit-btn mt-4" %>
    </div>
  </div> 
  
  <% end %>
</div>

app/views/inventories/show.html.erb
<div>
  <h1><%= @inventory.name %></h1>
  <div > <%= link_to 'Add food', new_inventory_inventory_food_path(current_user.id) %></div>
 <table class="table">
        <thead>
            <tr>
            <th >Food</th>
            <th >Quantity</th>
            <th >Price</th>
            <th >Actions</th>
            </tr>
        </thead>

        <tbody>
        <% @foods.each do |food|%>
            <tr>
            <td><%= food.food.name %></td>
            <td><%= food.quantity %></td>
            <td><%= food.food.price %></td>
            <td><%= button_to "Delete Food", inventory_inventory_food_path(@inventory, food.id), method: :delete, class: "btn btn-primary" %> </td>
            
            </tr>
            <% end %>
        </tbody>


        </table>

</div>

app/views/inventory_foods/new.html.erb
<div>
  <h2 class="heading">Add Inventory Food</h2>
<div>
<%= form_with model: [@inventory, @inventory.inventory_foods.create] do |f|%>
    <div>

    <div>
    <%= f.label "food" %><br>
    <%= f.collection_select :food_id, Food.all, :id, :name, prompt:true %><br>
    </div>


    <div>
    <%= f.label "quantity" %><br>
    <%= f.number_field :quantity, required: true, placeholder: '1',  min: 1%><br>
    </div>

    <div>
    <%= f.submit "Create Recipe_Food" %>
    </div>
    </div>
<%end%>
</div>
</div>

app/views/public_recipes/index.html.erb
<div>
<h1>Public recipes List</h1>

  <% @public_recipes.each do |pr| %>
    <div>
    <h2><%= pr.name %>by: <%= pr.user.name %></h2>  

     <p>Total food items: <%= @total_item%> </p>
   
    </div>
  <p>Total Price: <%= @prices %> </p>
    <p><%= pr.description %></p>
    <% end %>
  
    

</div>

app/views/public_recipes/new.html.erb
<h1>PublicRecipes#new</h1>
<p>Find me in app/views/public_recipes/new.html.erb</p>

app/views/public_recipes/show.html.erb
<h1>PublicRecipes#show</h1>
<p>Find me in app/views/public_recipes/show.html.erb</p>